### ISSUE TITLE
`edit` command creates a new revision even if file does not change

### ISSUE THREAD

**Issue by moz-astults** [mozilla-it/gsm-editor#3]
Steps to reproduce:
```
./gsm.py edit -p moz-fx-testapp1-nonprod -e stage
```
Without changing anything, just `:q` from the editor. Once the editor closes, `gsm-editor` says a new version has been created.

I think if nothing changes we should probably just exit without making a new version of the secret.

**Comment by cvalaas** [comment]
https://github.com/mozilla-it/gsm-editor/pull/4
